services:
  db:
    image: postgres:16
    container_name: pgdb-monkeymon
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: MonkeyMon
      POSTGRES_PASSWORD: MonkeyMon
      POSTGRES_DB: MonkeyMon_Blazor
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-monkeymon
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@monkey.de
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  local_pgdata:
  pgadmin-data: