// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyMon_Blazor.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonkeyMon_Blazor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241107095340_Species")]
    partial class Species
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Monkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Attack")
                        .HasColumnType("integer");

                    b.Property<int?>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<string>("KnownFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialDefense")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Monkeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("359c8461-1e1e-4546-bf1c-02e9447bb729"),
                            Attack = 624,
                            Defense = 515,
                            HealthPoints = 435,
                            KnownFrom = "Small Steel Cheese",
                            Name = "Lourdes",
                            SpecialAttack = 129,
                            SpecialDefense = 155,
                            Speed = 233
                        },
                        new
                        {
                            Id = new Guid("2863a05f-30bf-4c0f-91bd-0490e4778545"),
                            Attack = 336,
                            Defense = 42,
                            HealthPoints = 692,
                            KnownFrom = "Practical Concrete Towels",
                            Name = "Aylin",
                            SpecialAttack = 569,
                            SpecialDefense = 160,
                            Speed = 374
                        },
                        new
                        {
                            Id = new Guid("c5d553f4-47aa-44bd-8aa7-13b341fc7a86"),
                            Attack = 75,
                            Defense = 269,
                            HealthPoints = 200,
                            KnownFrom = "Rustic Concrete Table",
                            Name = "Michele",
                            SpecialAttack = 264,
                            SpecialDefense = 191,
                            Speed = 433
                        },
                        new
                        {
                            Id = new Guid("2aea6c54-b5b0-4c9c-b090-a90265c6baf4"),
                            Attack = 607,
                            Defense = 223,
                            HealthPoints = 281,
                            KnownFrom = "Unbranded Soft Fish",
                            Name = "Ines",
                            SpecialAttack = 108,
                            SpecialDefense = 240,
                            Speed = 201
                        },
                        new
                        {
                            Id = new Guid("f886cc16-9ae1-4a4d-9925-e58bd3a8e9aa"),
                            Attack = 147,
                            Defense = 387,
                            HealthPoints = 495,
                            KnownFrom = "Tasty Concrete Table",
                            Name = "Randi",
                            SpecialAttack = 581,
                            SpecialDefense = 254,
                            Speed = 690
                        },
                        new
                        {
                            Id = new Guid("3a8213fb-278f-4644-aec3-49e90309b83b"),
                            Attack = 113,
                            Defense = 413,
                            HealthPoints = 279,
                            KnownFrom = "Incredible Fresh Pizza",
                            Name = "Taryn",
                            SpecialAttack = 59,
                            SpecialDefense = 259,
                            Speed = 652
                        },
                        new
                        {
                            Id = new Guid("6ff27cc6-aed6-40e6-8530-29ff59e66727"),
                            Attack = 495,
                            Defense = 211,
                            HealthPoints = 630,
                            KnownFrom = "Gorgeous Metal Fish",
                            Name = "Emie",
                            SpecialAttack = 597,
                            SpecialDefense = 63,
                            Speed = 181
                        },
                        new
                        {
                            Id = new Guid("afc19488-f374-49df-8bbf-5b10f2ab54d2"),
                            Attack = 600,
                            Defense = 259,
                            HealthPoints = 673,
                            KnownFrom = "Refined Granite Shirt",
                            Name = "Rowena",
                            SpecialAttack = 480,
                            SpecialDefense = 184,
                            Speed = 578
                        },
                        new
                        {
                            Id = new Guid("3b08993c-a91d-48ff-bfea-8299f1314adb"),
                            Attack = 312,
                            Defense = 447,
                            HealthPoints = 165,
                            KnownFrom = "Refined Soft Keyboard",
                            Name = "Anahi",
                            SpecialAttack = 267,
                            SpecialDefense = 56,
                            Speed = 381
                        },
                        new
                        {
                            Id = new Guid("c4449798-4bf3-444e-b156-982d7bde79d8"),
                            Attack = 527,
                            Defense = 135,
                            HealthPoints = 125,
                            KnownFrom = "Small Soft Bike",
                            Name = "Abagail",
                            SpecialAttack = 531,
                            SpecialDefense = 166,
                            Speed = 467
                        },
                        new
                        {
                            Id = new Guid("b8585420-bba8-4727-bf3e-d23e76180160"),
                            Attack = 370,
                            Defense = 566,
                            HealthPoints = 191,
                            KnownFrom = "Sleek Plastic Bacon",
                            Name = "Evan",
                            SpecialAttack = 476,
                            SpecialDefense = 451,
                            Speed = 569
                        },
                        new
                        {
                            Id = new Guid("ef4d684e-5308-4081-a875-ce4afdea8ec1"),
                            Attack = 23,
                            Defense = 333,
                            HealthPoints = 69,
                            KnownFrom = "Incredible Fresh Shoes",
                            Name = "Hermann",
                            SpecialAttack = 129,
                            SpecialDefense = 350,
                            Speed = 608
                        },
                        new
                        {
                            Id = new Guid("dc22fdb5-71f4-43d1-bb49-83e30bad9486"),
                            Attack = 387,
                            Defense = 615,
                            HealthPoints = 208,
                            KnownFrom = "Rustic Plastic Mouse",
                            Name = "Emilie",
                            SpecialAttack = 456,
                            SpecialDefense = 639,
                            Speed = 808
                        },
                        new
                        {
                            Id = new Guid("5dde1a39-50e4-44cc-8234-024b9c719613"),
                            Attack = 230,
                            Defense = 502,
                            HealthPoints = 333,
                            KnownFrom = "Rustic Fresh Towels",
                            Name = "Brando",
                            SpecialAttack = 293,
                            SpecialDefense = 290,
                            Speed = 435
                        },
                        new
                        {
                            Id = new Guid("6d67fb36-092d-4f3b-9fe8-ca41458a5549"),
                            Attack = 132,
                            Defense = 265,
                            HealthPoints = 472,
                            KnownFrom = "Refined Steel Bacon",
                            Name = "Gideon",
                            SpecialAttack = 73,
                            SpecialDefense = 146,
                            Speed = 804
                        },
                        new
                        {
                            Id = new Guid("31939275-0234-4ff7-92a2-09ee7d12634e"),
                            Attack = 712,
                            Defense = 403,
                            HealthPoints = 536,
                            KnownFrom = "Rustic Rubber Towels",
                            Name = "Lempi",
                            SpecialAttack = 117,
                            SpecialDefense = 366,
                            Speed = 577
                        },
                        new
                        {
                            Id = new Guid("a3587725-0477-4b1a-8f27-bb2f95076269"),
                            Attack = 672,
                            Defense = 642,
                            HealthPoints = 158,
                            KnownFrom = "Rustic Wooden Chips",
                            Name = "Agnes",
                            SpecialAttack = 108,
                            SpecialDefense = 383,
                            Speed = 47
                        },
                        new
                        {
                            Id = new Guid("2271a4eb-4d90-4f5a-8d46-a4305c543f8e"),
                            Attack = 423,
                            Defense = 507,
                            HealthPoints = 55,
                            KnownFrom = "Ergonomic Rubber Tuna",
                            Name = "Okey",
                            SpecialAttack = 170,
                            SpecialDefense = 162,
                            Speed = 622
                        },
                        new
                        {
                            Id = new Guid("abaf2d0c-03e8-481b-873a-698559593641"),
                            Attack = 151,
                            Defense = 440,
                            HealthPoints = 331,
                            KnownFrom = "Rustic Wooden Sausages",
                            Name = "Claudine",
                            SpecialAttack = 118,
                            SpecialDefense = 511,
                            Speed = 200
                        },
                        new
                        {
                            Id = new Guid("6aadb1ba-b31f-44e5-879c-585e034f0634"),
                            Attack = 362,
                            Defense = 458,
                            HealthPoints = 440,
                            KnownFrom = "Gorgeous Metal Cheese",
                            Name = "Eldora",
                            SpecialAttack = 485,
                            SpecialDefense = 638,
                            Speed = 770
                        },
                        new
                        {
                            Id = new Guid("19ba97a5-f7ba-4ed2-9090-8590fe4cc0ca"),
                            Attack = 624,
                            Defense = 554,
                            HealthPoints = 146,
                            KnownFrom = "Ergonomic Plastic Bacon",
                            Name = "Fiona",
                            SpecialAttack = 442,
                            SpecialDefense = 71,
                            Speed = 174
                        },
                        new
                        {
                            Id = new Guid("c1fbc259-b81e-48e5-b9b0-bc81acd63023"),
                            Attack = 24,
                            Defense = 464,
                            HealthPoints = 319,
                            KnownFrom = "Handmade Fresh Mouse",
                            Name = "Myrtice",
                            SpecialAttack = 195,
                            SpecialDefense = 368,
                            Speed = 416
                        },
                        new
                        {
                            Id = new Guid("a332c11a-2c33-4f0f-b2b9-67630c5b5759"),
                            Attack = 399,
                            Defense = 164,
                            HealthPoints = 352,
                            KnownFrom = "Rustic Soft Bike",
                            Name = "Scottie",
                            SpecialAttack = 261,
                            SpecialDefense = 386,
                            Speed = 396
                        },
                        new
                        {
                            Id = new Guid("d893c490-aca8-468b-a65c-21e6cb177efe"),
                            Attack = 700,
                            Defense = 426,
                            HealthPoints = 277,
                            KnownFrom = "Handcrafted Cotton Ball",
                            Name = "Jules",
                            SpecialAttack = 485,
                            SpecialDefense = 454,
                            Speed = 193
                        },
                        new
                        {
                            Id = new Guid("5dba6f82-7994-4df7-82de-5b354ae76f43"),
                            Attack = 403,
                            Defense = 397,
                            HealthPoints = 108,
                            KnownFrom = "Awesome Metal Hat",
                            Name = "Keaton",
                            SpecialAttack = 571,
                            SpecialDefense = 480,
                            Speed = 590
                        },
                        new
                        {
                            Id = new Guid("f9f8a8c0-3455-4dfd-ace6-b9ee06d5a8ea"),
                            Attack = 379,
                            Defense = 405,
                            HealthPoints = 596,
                            KnownFrom = "Refined Cotton Computer",
                            Name = "Jessika",
                            SpecialAttack = 361,
                            SpecialDefense = 375,
                            Speed = 370
                        },
                        new
                        {
                            Id = new Guid("2af24052-147d-444c-bbe2-dc12e8641ae4"),
                            Attack = 284,
                            Defense = 269,
                            HealthPoints = 222,
                            KnownFrom = "Refined Cotton Bike",
                            Name = "Marisa",
                            SpecialAttack = 497,
                            SpecialDefense = 54,
                            Speed = 651
                        },
                        new
                        {
                            Id = new Guid("cbface08-5b47-4ec4-b239-039a5b266f3b"),
                            Attack = 358,
                            Defense = 20,
                            HealthPoints = 19,
                            KnownFrom = "Licensed Frozen Computer",
                            Name = "Mireya",
                            SpecialAttack = 508,
                            SpecialDefense = 285,
                            Speed = 536
                        },
                        new
                        {
                            Id = new Guid("403f79a4-606c-462f-94a9-d90b3ccbcb71"),
                            Attack = 61,
                            Defense = 259,
                            HealthPoints = 654,
                            KnownFrom = "Fantastic Wooden Salad",
                            Name = "Vance",
                            SpecialAttack = 607,
                            SpecialDefense = 146,
                            Speed = 795
                        },
                        new
                        {
                            Id = new Guid("8565b289-0f98-4c19-ac8f-49baaf50f274"),
                            Attack = 333,
                            Defense = 219,
                            HealthPoints = 412,
                            KnownFrom = "Awesome Soft Chips",
                            Name = "Janae",
                            SpecialAttack = 435,
                            SpecialDefense = 314,
                            Speed = 16
                        },
                        new
                        {
                            Id = new Guid("25a2f341-7507-4161-a536-1c5b29230684"),
                            Attack = 21,
                            Defense = 180,
                            HealthPoints = 158,
                            KnownFrom = "Practical Rubber Fish",
                            Name = "Sister",
                            SpecialAttack = 413,
                            SpecialDefense = 8,
                            Speed = 714
                        },
                        new
                        {
                            Id = new Guid("4faadc77-d370-4684-9e52-7e8c2724d83d"),
                            Attack = 559,
                            Defense = 282,
                            HealthPoints = 3,
                            KnownFrom = "Incredible Frozen Chair",
                            Name = "Mia",
                            SpecialAttack = 156,
                            SpecialDefense = 370,
                            Speed = 291
                        },
                        new
                        {
                            Id = new Guid("ea5ecd5d-71bf-424e-94b3-791c0d733452"),
                            Attack = 528,
                            Defense = 101,
                            HealthPoints = 272,
                            KnownFrom = "Rustic Frozen Pizza",
                            Name = "Carlie",
                            SpecialAttack = 607,
                            SpecialDefense = 399,
                            Speed = 215
                        },
                        new
                        {
                            Id = new Guid("4acd77f2-7fb0-4893-bbab-f36458b2c5e0"),
                            Attack = 77,
                            Defense = 444,
                            HealthPoints = 495,
                            KnownFrom = "Ergonomic Cotton Cheese",
                            Name = "Mireille",
                            SpecialAttack = 333,
                            SpecialDefense = 161,
                            Speed = 87
                        },
                        new
                        {
                            Id = new Guid("d079a89f-798e-4827-8750-c09e5516e2c5"),
                            Attack = 644,
                            Defense = 269,
                            HealthPoints = 167,
                            KnownFrom = "Gorgeous Granite Towels",
                            Name = "Flavio",
                            SpecialAttack = 544,
                            SpecialDefense = 61,
                            Speed = 171
                        },
                        new
                        {
                            Id = new Guid("7fd91804-89d1-449e-b28b-25145d23a5e5"),
                            Attack = 45,
                            Defense = 324,
                            HealthPoints = 166,
                            KnownFrom = "Unbranded Cotton Gloves",
                            Name = "Akeem",
                            SpecialAttack = 487,
                            SpecialDefense = 313,
                            Speed = 35
                        },
                        new
                        {
                            Id = new Guid("39b6c3c3-3f78-42e7-9e7d-e997d2b7e423"),
                            Attack = 70,
                            Defense = 392,
                            HealthPoints = 459,
                            KnownFrom = "Generic Frozen Cheese",
                            Name = "Maryam",
                            SpecialAttack = 97,
                            SpecialDefense = 344,
                            Speed = 226
                        },
                        new
                        {
                            Id = new Guid("0c71a292-d9f2-45dc-b19e-34c821782d7a"),
                            Attack = 128,
                            Defense = 508,
                            HealthPoints = 152,
                            KnownFrom = "Unbranded Frozen Salad",
                            Name = "Eva",
                            SpecialAttack = 142,
                            SpecialDefense = 54,
                            Speed = 605
                        },
                        new
                        {
                            Id = new Guid("a53f3353-2220-4929-8fa8-f90b27c1f574"),
                            Attack = 567,
                            Defense = 163,
                            HealthPoints = 337,
                            KnownFrom = "Sleek Rubber Soap",
                            Name = "Olin",
                            SpecialAttack = 166,
                            SpecialDefense = 306,
                            Speed = 555
                        },
                        new
                        {
                            Id = new Guid("dfe20b8d-43de-47f8-a269-cae227d8bbee"),
                            Attack = 458,
                            Defense = 571,
                            HealthPoints = 707,
                            KnownFrom = "Refined Rubber Shoes",
                            Name = "Junius",
                            SpecialAttack = 435,
                            SpecialDefense = 494,
                            Speed = 103
                        },
                        new
                        {
                            Id = new Guid("ea2758a8-5278-4b72-86b4-8eedaf217144"),
                            Attack = 160,
                            Defense = 125,
                            HealthPoints = 174,
                            KnownFrom = "Handmade Wooden Keyboard",
                            Name = "Lillie",
                            SpecialAttack = 416,
                            SpecialDefense = 39,
                            Speed = 610
                        },
                        new
                        {
                            Id = new Guid("fd8d7100-f6c0-41c8-aeb5-ce3766f293e2"),
                            Attack = 621,
                            Defense = 279,
                            HealthPoints = 490,
                            KnownFrom = "Rustic Granite Chips",
                            Name = "Bernadette",
                            SpecialAttack = 67,
                            SpecialDefense = 63,
                            Speed = 415
                        },
                        new
                        {
                            Id = new Guid("f5a97344-3059-4970-81c8-a6f9ef2e7365"),
                            Attack = 95,
                            Defense = 276,
                            HealthPoints = 246,
                            KnownFrom = "Generic Wooden Gloves",
                            Name = "Lucio",
                            SpecialAttack = 366,
                            SpecialDefense = 333,
                            Speed = 804
                        },
                        new
                        {
                            Id = new Guid("8ef29eed-d630-4a67-8c0f-68fe96c00668"),
                            Attack = 659,
                            Defense = 586,
                            HealthPoints = 449,
                            KnownFrom = "Refined Concrete Car",
                            Name = "Clement",
                            SpecialAttack = 231,
                            SpecialDefense = 487,
                            Speed = 813
                        },
                        new
                        {
                            Id = new Guid("57ceac89-c75b-42da-a591-227b3d890532"),
                            Attack = 657,
                            Defense = 70,
                            HealthPoints = 70,
                            KnownFrom = "Handmade Fresh Soap",
                            Name = "Ruth",
                            SpecialAttack = 561,
                            SpecialDefense = 478,
                            Speed = 349
                        },
                        new
                        {
                            Id = new Guid("82026875-2daa-4199-ab30-f78a5f139875"),
                            Attack = 687,
                            Defense = 259,
                            HealthPoints = 337,
                            KnownFrom = "Tasty Metal Soap",
                            Name = "Katharina",
                            SpecialAttack = 237,
                            SpecialDefense = 538,
                            Speed = 836
                        },
                        new
                        {
                            Id = new Guid("10ea61a5-ae0f-4d3f-b4b1-4ef9f9fefb72"),
                            Attack = 484,
                            Defense = 365,
                            HealthPoints = 26,
                            KnownFrom = "Tasty Rubber Fish",
                            Name = "Priscilla",
                            SpecialAttack = 93,
                            SpecialDefense = 103,
                            Speed = 836
                        },
                        new
                        {
                            Id = new Guid("4ae45a15-96e0-4b5b-9906-95b12603746d"),
                            Attack = 45,
                            Defense = 211,
                            HealthPoints = 89,
                            KnownFrom = "Tasty Cotton Pants",
                            Name = "Katelyn",
                            SpecialAttack = 104,
                            SpecialDefense = 384,
                            Speed = 91
                        },
                        new
                        {
                            Id = new Guid("160021fd-c698-4465-bc59-4fe39eb3d5f7"),
                            Attack = 619,
                            Defense = 41,
                            HealthPoints = 557,
                            KnownFrom = "Small Concrete Towels",
                            Name = "Joaquin",
                            SpecialAttack = 241,
                            SpecialDefense = 330,
                            Speed = 419
                        },
                        new
                        {
                            Id = new Guid("6909eb90-c59b-4582-b48b-04d35cdd897b"),
                            Attack = 9,
                            Defense = 371,
                            HealthPoints = 177,
                            KnownFrom = "Practical Frozen Table",
                            Name = "Albin",
                            SpecialAttack = 546,
                            SpecialDefense = 542,
                            Speed = 567
                        },
                        new
                        {
                            Id = new Guid("9ae78d7d-41df-4c77-b6db-deecb391f554"),
                            Attack = 31,
                            Defense = 408,
                            HealthPoints = 419,
                            KnownFrom = "Fantastic Rubber Tuna",
                            Name = "Lucius",
                            SpecialAttack = 295,
                            SpecialDefense = 115,
                            Speed = 779
                        },
                        new
                        {
                            Id = new Guid("781d48c2-1e4f-4f8a-ac5d-73d35ebe2ba2"),
                            Attack = 447,
                            Defense = 614,
                            HealthPoints = 387,
                            KnownFrom = "Small Metal Mouse",
                            Name = "Alejandrin",
                            SpecialAttack = 279,
                            SpecialDefense = 232,
                            Speed = 712
                        },
                        new
                        {
                            Id = new Guid("61ff2fa8-3d38-43ff-8bd3-224bccf9c8ee"),
                            Attack = 307,
                            Defense = 48,
                            HealthPoints = 492,
                            KnownFrom = "Tasty Wooden Mouse",
                            Name = "Sven",
                            SpecialAttack = 350,
                            SpecialDefense = 408,
                            Speed = 205
                        },
                        new
                        {
                            Id = new Guid("d1e6eda2-40e6-4378-aa63-dae2d6d8e1e0"),
                            Attack = 714,
                            Defense = 364,
                            HealthPoints = 396,
                            KnownFrom = "Licensed Plastic Tuna",
                            Name = "Isabelle",
                            SpecialAttack = 545,
                            SpecialDefense = 632,
                            Speed = 67
                        },
                        new
                        {
                            Id = new Guid("2a9d1ab9-d3b6-426a-a5c0-16d1c1c17d3d"),
                            Attack = 52,
                            Defense = 449,
                            HealthPoints = 147,
                            KnownFrom = "Gorgeous Fresh Soap",
                            Name = "Era",
                            SpecialAttack = 428,
                            SpecialDefense = 296,
                            Speed = 125
                        },
                        new
                        {
                            Id = new Guid("077d575f-0771-4ce0-b4c9-1f28b9ffc791"),
                            Attack = 26,
                            Defense = 180,
                            HealthPoints = 290,
                            KnownFrom = "Gorgeous Metal Ball",
                            Name = "Penelope",
                            SpecialAttack = 20,
                            SpecialDefense = 446,
                            Speed = 764
                        },
                        new
                        {
                            Id = new Guid("0f85bc8d-2be1-490e-8f1b-4562af7f1963"),
                            Attack = 266,
                            Defense = 548,
                            HealthPoints = 273,
                            KnownFrom = "Unbranded Steel Table",
                            Name = "Modesta",
                            SpecialAttack = 91,
                            SpecialDefense = 71,
                            Speed = 74
                        },
                        new
                        {
                            Id = new Guid("e12281a5-5fc4-481f-b177-c0011c73340c"),
                            Attack = 144,
                            Defense = 251,
                            HealthPoints = 93,
                            KnownFrom = "Tasty Concrete Bacon",
                            Name = "Ola",
                            SpecialAttack = 29,
                            SpecialDefense = 204,
                            Speed = 298
                        },
                        new
                        {
                            Id = new Guid("2b8c9038-b000-4fb0-929a-101eb751f204"),
                            Attack = 180,
                            Defense = 442,
                            HealthPoints = 47,
                            KnownFrom = "Intelligent Rubber Chair",
                            Name = "Junius",
                            SpecialAttack = 511,
                            SpecialDefense = 175,
                            Speed = 99
                        },
                        new
                        {
                            Id = new Guid("74fcdffc-fd2a-4b2f-b04d-df98fa212974"),
                            Attack = 129,
                            Defense = 248,
                            HealthPoints = 684,
                            KnownFrom = "Tasty Steel Mouse",
                            Name = "Franz",
                            SpecialAttack = 228,
                            SpecialDefense = 147,
                            Speed = 397
                        },
                        new
                        {
                            Id = new Guid("ff4c35a0-6b02-435b-8c8b-a8ed874d4838"),
                            Attack = 414,
                            Defense = 405,
                            HealthPoints = 653,
                            KnownFrom = "Incredible Cotton Sausages",
                            Name = "Jacquelyn",
                            SpecialAttack = 366,
                            SpecialDefense = 360,
                            Speed = 470
                        },
                        new
                        {
                            Id = new Guid("8170878a-ea59-41e5-8882-08c4af4e7ec6"),
                            Attack = 597,
                            Defense = 371,
                            HealthPoints = 488,
                            KnownFrom = "Refined Cotton Chicken",
                            Name = "Dale",
                            SpecialAttack = 461,
                            SpecialDefense = 433,
                            Speed = 648
                        },
                        new
                        {
                            Id = new Guid("c312c1ec-9c81-4def-bec7-e48798b79fde"),
                            Attack = 248,
                            Defense = 137,
                            HealthPoints = 68,
                            KnownFrom = "Incredible Concrete Sausages",
                            Name = "Dion",
                            SpecialAttack = 431,
                            SpecialDefense = 314,
                            Speed = 482
                        },
                        new
                        {
                            Id = new Guid("cb3d0f03-eb49-4611-bf7c-21b28a0dc2fc"),
                            Attack = 383,
                            Defense = 292,
                            HealthPoints = 604,
                            KnownFrom = "Gorgeous Metal Gloves",
                            Name = "Ada",
                            SpecialAttack = 85,
                            SpecialDefense = 94,
                            Speed = 771
                        },
                        new
                        {
                            Id = new Guid("40263c72-835b-4b22-9037-17cfe641dc22"),
                            Attack = 215,
                            Defense = 38,
                            HealthPoints = 129,
                            KnownFrom = "Licensed Plastic Mouse",
                            Name = "Tyrel",
                            SpecialAttack = 110,
                            SpecialDefense = 605,
                            Speed = 718
                        },
                        new
                        {
                            Id = new Guid("ca5597b5-dfb8-4ae6-8bfa-3885738817e6"),
                            Attack = 202,
                            Defense = 111,
                            HealthPoints = 149,
                            KnownFrom = "Handmade Rubber Sausages",
                            Name = "Berenice",
                            SpecialAttack = 78,
                            SpecialDefense = 604,
                            Speed = 646
                        },
                        new
                        {
                            Id = new Guid("4df05b80-5c5a-49a9-8ffb-5fbf4100c09b"),
                            Attack = 229,
                            Defense = 454,
                            HealthPoints = 49,
                            KnownFrom = "Licensed Steel Computer",
                            Name = "Conner",
                            SpecialAttack = 475,
                            SpecialDefense = 361,
                            Speed = 61
                        },
                        new
                        {
                            Id = new Guid("a3be1baa-8948-45e0-ae61-6c4c2b981b40"),
                            Attack = 366,
                            Defense = 248,
                            HealthPoints = 597,
                            KnownFrom = "Sleek Fresh Bike",
                            Name = "Davion",
                            SpecialAttack = 8,
                            SpecialDefense = 314,
                            Speed = 160
                        },
                        new
                        {
                            Id = new Guid("e856d582-bd60-4599-bc14-3014787e5dc8"),
                            Attack = 18,
                            Defense = 327,
                            HealthPoints = 209,
                            KnownFrom = "Small Metal Fish",
                            Name = "Elinor",
                            SpecialAttack = 162,
                            SpecialDefense = 38,
                            Speed = 36
                        },
                        new
                        {
                            Id = new Guid("0da1b390-3ee1-4722-b310-d0463a3d797f"),
                            Attack = 307,
                            Defense = 195,
                            HealthPoints = 704,
                            KnownFrom = "Generic Cotton Tuna",
                            Name = "Leon",
                            SpecialAttack = 207,
                            SpecialDefense = 61,
                            Speed = 852
                        },
                        new
                        {
                            Id = new Guid("df9a2ec0-a420-46d2-a6ae-55ae085cd00a"),
                            Attack = 102,
                            Defense = 524,
                            HealthPoints = 704,
                            KnownFrom = "Intelligent Wooden Chicken",
                            Name = "Kirstin",
                            SpecialAttack = 233,
                            SpecialDefense = 180,
                            Speed = 18
                        },
                        new
                        {
                            Id = new Guid("02434c2a-b52a-475e-9a7f-e046d98ec855"),
                            Attack = 320,
                            Defense = 269,
                            HealthPoints = 397,
                            KnownFrom = "Handcrafted Cotton Salad",
                            Name = "Frieda",
                            SpecialAttack = 75,
                            SpecialDefense = 501,
                            Speed = 621
                        },
                        new
                        {
                            Id = new Guid("2f00264c-63b0-47ad-9609-3dcf925cc88a"),
                            Attack = 720,
                            Defense = 488,
                            HealthPoints = 151,
                            KnownFrom = "Small Soft Mouse",
                            Name = "Thurman",
                            SpecialAttack = 16,
                            SpecialDefense = 529,
                            Speed = 700
                        },
                        new
                        {
                            Id = new Guid("62fd8335-89d2-44d7-ac3e-7e6a4528fd2a"),
                            Attack = 182,
                            Defense = 531,
                            HealthPoints = 246,
                            KnownFrom = "Fantastic Wooden Bike",
                            Name = "Tristian",
                            SpecialAttack = 594,
                            SpecialDefense = 514,
                            Speed = 751
                        },
                        new
                        {
                            Id = new Guid("0fece278-06a5-4360-9302-157fedbe4771"),
                            Attack = 175,
                            Defense = 188,
                            HealthPoints = 712,
                            KnownFrom = "Intelligent Cotton Bike",
                            Name = "Jamarcus",
                            SpecialAttack = 545,
                            SpecialDefense = 643,
                            Speed = 657
                        },
                        new
                        {
                            Id = new Guid("1ad30b09-0d2e-42e3-92bd-ee7552c57842"),
                            Attack = 395,
                            Defense = 159,
                            HealthPoints = 385,
                            KnownFrom = "Fantastic Fresh Pizza",
                            Name = "Heaven",
                            SpecialAttack = 356,
                            SpecialDefense = 502,
                            Speed = 496
                        },
                        new
                        {
                            Id = new Guid("f18f05a2-a493-4134-b7c9-69bb6c7a7dfc"),
                            Attack = 157,
                            Defense = 584,
                            HealthPoints = 508,
                            KnownFrom = "Fantastic Concrete Sausages",
                            Name = "Olen",
                            SpecialAttack = 39,
                            SpecialDefense = 637,
                            Speed = 206
                        },
                        new
                        {
                            Id = new Guid("79546b53-f86c-4b95-b792-f60808503545"),
                            Attack = 160,
                            Defense = 153,
                            HealthPoints = 377,
                            KnownFrom = "Rustic Granite Chips",
                            Name = "Thaddeus",
                            SpecialAttack = 502,
                            SpecialDefense = 380,
                            Speed = 728
                        },
                        new
                        {
                            Id = new Guid("54facaa0-811b-44d9-bc4f-b949a1baa3d1"),
                            Attack = 543,
                            Defense = 598,
                            HealthPoints = 35,
                            KnownFrom = "Handcrafted Metal Bike",
                            Name = "Izaiah",
                            SpecialAttack = 57,
                            SpecialDefense = 535,
                            Speed = 296
                        },
                        new
                        {
                            Id = new Guid("a5e2b3a4-a6b9-4a1c-b48d-8cdc771c87d6"),
                            Attack = 530,
                            Defense = 158,
                            HealthPoints = 46,
                            KnownFrom = "Fantastic Fresh Bacon",
                            Name = "Emma",
                            SpecialAttack = 525,
                            SpecialDefense = 233,
                            Speed = 71
                        },
                        new
                        {
                            Id = new Guid("8fb60518-0c89-4682-9805-4c601a02e69c"),
                            Attack = 352,
                            Defense = 190,
                            HealthPoints = 646,
                            KnownFrom = "Rustic Wooden Keyboard",
                            Name = "Rita",
                            SpecialAttack = 534,
                            SpecialDefense = 646,
                            Speed = 665
                        },
                        new
                        {
                            Id = new Guid("9b2e7c21-a0c8-4128-b05a-cf72301198f9"),
                            Attack = 546,
                            Defense = 570,
                            HealthPoints = 645,
                            KnownFrom = "Intelligent Wooden Cheese",
                            Name = "Ariel",
                            SpecialAttack = 419,
                            SpecialDefense = 114,
                            Speed = 773
                        },
                        new
                        {
                            Id = new Guid("12b9a929-3edc-4b79-8c8d-52e8d767ae44"),
                            Attack = 404,
                            Defense = 260,
                            HealthPoints = 360,
                            KnownFrom = "Handcrafted Fresh Tuna",
                            Name = "Tina",
                            SpecialAttack = 321,
                            SpecialDefense = 354,
                            Speed = 462
                        },
                        new
                        {
                            Id = new Guid("5649b087-70d2-40b4-b55f-cf59dd8cdf98"),
                            Attack = 196,
                            Defense = 446,
                            HealthPoints = 541,
                            KnownFrom = "Ergonomic Plastic Salad",
                            Name = "Rafael",
                            SpecialAttack = 151,
                            SpecialDefense = 146,
                            Speed = 511
                        },
                        new
                        {
                            Id = new Guid("895dbdd1-50d3-48b3-9c53-85c66c8dbf2f"),
                            Attack = 315,
                            Defense = 163,
                            HealthPoints = 591,
                            KnownFrom = "Refined Plastic Keyboard",
                            Name = "Lina",
                            SpecialAttack = 81,
                            SpecialDefense = 433,
                            Speed = 79
                        },
                        new
                        {
                            Id = new Guid("7ea984d9-c715-41ac-8cfe-36d98193c283"),
                            Attack = 507,
                            Defense = 233,
                            HealthPoints = 562,
                            KnownFrom = "Gorgeous Wooden Bike",
                            Name = "Clemmie",
                            SpecialAttack = 124,
                            SpecialDefense = 188,
                            Speed = 493
                        },
                        new
                        {
                            Id = new Guid("d6dbcdaf-9593-404b-bfc6-76b80e1afcf5"),
                            Attack = 154,
                            Defense = 642,
                            HealthPoints = 462,
                            KnownFrom = "Intelligent Steel Bacon",
                            Name = "Jeffrey",
                            SpecialAttack = 588,
                            SpecialDefense = 84,
                            Speed = 681
                        },
                        new
                        {
                            Id = new Guid("ad1f7574-9da0-4470-bf8d-72a127d90c0a"),
                            Attack = 559,
                            Defense = 475,
                            HealthPoints = 182,
                            KnownFrom = "Generic Frozen Gloves",
                            Name = "Daniella",
                            SpecialAttack = 467,
                            SpecialDefense = 174,
                            Speed = 169
                        },
                        new
                        {
                            Id = new Guid("0fbad9fe-1618-403b-81f9-9c856b39336d"),
                            Attack = 667,
                            Defense = 88,
                            HealthPoints = 539,
                            KnownFrom = "Small Metal Keyboard",
                            Name = "Kelsi",
                            SpecialAttack = 156,
                            SpecialDefense = 449,
                            Speed = 374
                        },
                        new
                        {
                            Id = new Guid("e99177a0-69da-4ee2-a0dc-0f486df1bf71"),
                            Attack = 108,
                            Defense = 339,
                            HealthPoints = 427,
                            KnownFrom = "Fantastic Fresh Mouse",
                            Name = "Raphael",
                            SpecialAttack = 85,
                            SpecialDefense = 226,
                            Speed = 131
                        },
                        new
                        {
                            Id = new Guid("fb5a8688-7f5d-4c3f-a3ba-b7d46363c408"),
                            Attack = 669,
                            Defense = 514,
                            HealthPoints = 383,
                            KnownFrom = "Rustic Cotton Keyboard",
                            Name = "Jordan",
                            SpecialAttack = 581,
                            SpecialDefense = 275,
                            Speed = 271
                        },
                        new
                        {
                            Id = new Guid("3a16f152-549f-44aa-869b-ccc1d68a4b0a"),
                            Attack = 707,
                            Defense = 64,
                            HealthPoints = 515,
                            KnownFrom = "Unbranded Plastic Salad",
                            Name = "Veronica",
                            SpecialAttack = 376,
                            SpecialDefense = 416,
                            Speed = 520
                        },
                        new
                        {
                            Id = new Guid("f346d2e2-a107-4630-a767-bfc7462d057a"),
                            Attack = 15,
                            Defense = 621,
                            HealthPoints = 651,
                            KnownFrom = "Tasty Rubber Hat",
                            Name = "Celine",
                            SpecialAttack = 245,
                            SpecialDefense = 313,
                            Speed = 553
                        });
                });

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Taxonomy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Monkey", b =>
                {
                    b.HasOne("MonkeyMon_Blazor.Models.Species", "Species")
                        .WithMany("Monkeys")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Species");
                });

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Species", b =>
                {
                    b.Navigation("Monkeys");
                });
#pragma warning restore 612, 618
        }
    }
}
