// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyMon_Blazor.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonkeyMon_Blazor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241106124610_Monkey")]
    partial class Monkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Monkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Attack")
                        .HasColumnType("integer");

                    b.Property<int?>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<string>("KnownFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Monkeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c936eb40-1b4f-4e60-a863-b896b157acce"),
                            Attack = 578,
                            Defense = 296,
                            HealthPoints = 581,
                            KnownFrom = "Sleek Cotton Tuna",
                            Name = "Alison",
                            SpecialAttack = 289,
                            SpecialDefense = 511,
                            Speed = 647
                        },
                        new
                        {
                            Id = new Guid("9c61cc7e-cf26-4eb2-a954-b60663e44dbc"),
                            Attack = 637,
                            Defense = 637,
                            HealthPoints = 669,
                            KnownFrom = "Generic Concrete Towels",
                            Name = "Tracey",
                            SpecialAttack = 16,
                            SpecialDefense = 330,
                            Speed = 695
                        },
                        new
                        {
                            Id = new Guid("c246c1bf-bf90-42e0-84a9-27203dcdba18"),
                            Attack = 599,
                            Defense = 31,
                            HealthPoints = 98,
                            KnownFrom = "Awesome Wooden Chicken",
                            Name = "Einar",
                            SpecialAttack = 570,
                            SpecialDefense = 648,
                            Speed = 475
                        },
                        new
                        {
                            Id = new Guid("fa08f5c0-8ab9-443b-ab17-d0efdf702f1d"),
                            Attack = 84,
                            Defense = 170,
                            HealthPoints = 44,
                            KnownFrom = "Sleek Steel Shirt",
                            Name = "Janessa",
                            SpecialAttack = 54,
                            SpecialDefense = 434,
                            Speed = 68
                        },
                        new
                        {
                            Id = new Guid("26a2f697-6afa-403d-88e7-2bb259e79951"),
                            Attack = 391,
                            Defense = 379,
                            HealthPoints = 647,
                            KnownFrom = "Intelligent Fresh Computer",
                            Name = "Broderick",
                            SpecialAttack = 411,
                            SpecialDefense = 137,
                            Speed = 335
                        },
                        new
                        {
                            Id = new Guid("941ff88d-7986-4e21-8689-5b8fc2ce3b41"),
                            Attack = 53,
                            Defense = 594,
                            HealthPoints = 706,
                            KnownFrom = "Practical Rubber Table",
                            Name = "Willa",
                            SpecialAttack = 176,
                            SpecialDefense = 562,
                            Speed = 162
                        },
                        new
                        {
                            Id = new Guid("5e4350f2-399c-4c61-9ec1-b569b7938b00"),
                            Attack = 99,
                            Defense = 274,
                            HealthPoints = 105,
                            KnownFrom = "Sleek Cotton Bike",
                            Name = "Princess",
                            SpecialAttack = 357,
                            SpecialDefense = 251,
                            Speed = 330
                        },
                        new
                        {
                            Id = new Guid("d4a6a17d-88d2-4c0c-b198-cb57f74740e5"),
                            Attack = 624,
                            Defense = 221,
                            HealthPoints = 101,
                            KnownFrom = "Intelligent Soft Soap",
                            Name = "Breanna",
                            SpecialAttack = 390,
                            SpecialDefense = 565,
                            Speed = 128
                        },
                        new
                        {
                            Id = new Guid("76c78e71-4fc5-4ec6-bc84-963fb0f2f6f3"),
                            Attack = 221,
                            Defense = 127,
                            HealthPoints = 319,
                            KnownFrom = "Awesome Granite Chair",
                            Name = "Deion",
                            SpecialAttack = 23,
                            SpecialDefense = 335,
                            Speed = 248
                        },
                        new
                        {
                            Id = new Guid("0c905979-8a8d-4fc9-88bc-899c3fec0181"),
                            Attack = 5,
                            Defense = 57,
                            HealthPoints = 656,
                            KnownFrom = "Licensed Fresh Chicken",
                            Name = "Krista",
                            SpecialAttack = 3,
                            SpecialDefense = 76,
                            Speed = 398
                        },
                        new
                        {
                            Id = new Guid("bd0c8d06-8556-492e-932b-bc515b9a91fe"),
                            Attack = 456,
                            Defense = 26,
                            HealthPoints = 616,
                            KnownFrom = "Unbranded Wooden Chips",
                            Name = "Caleb",
                            SpecialAttack = 501,
                            SpecialDefense = 595,
                            Speed = 424
                        },
                        new
                        {
                            Id = new Guid("d45917c6-d8e2-494e-aa27-cf34c874b8e8"),
                            Attack = 376,
                            Defense = 82,
                            HealthPoints = 411,
                            KnownFrom = "Gorgeous Fresh Mouse",
                            Name = "Evert",
                            SpecialAttack = 589,
                            SpecialDefense = 305,
                            Speed = 181
                        },
                        new
                        {
                            Id = new Guid("e0cb159d-fd7f-4d9f-bc65-3fd3bfad6f96"),
                            Attack = 350,
                            Defense = 248,
                            HealthPoints = 531,
                            KnownFrom = "Unbranded Plastic Computer",
                            Name = "Deontae",
                            SpecialAttack = 409,
                            SpecialDefense = 599,
                            Speed = 341
                        },
                        new
                        {
                            Id = new Guid("26127784-a9cf-4557-9f8e-95cfe83f2e52"),
                            Attack = 594,
                            Defense = 419,
                            HealthPoints = 228,
                            KnownFrom = "Gorgeous Plastic Car",
                            Name = "Alanna",
                            SpecialAttack = 367,
                            SpecialDefense = 11,
                            Speed = 238
                        },
                        new
                        {
                            Id = new Guid("008db3ac-ec58-4231-a814-279c0a8beec9"),
                            Attack = 262,
                            Defense = 472,
                            HealthPoints = 713,
                            KnownFrom = "Fantastic Cotton Soap",
                            Name = "Noble",
                            SpecialAttack = 202,
                            SpecialDefense = 452,
                            Speed = 260
                        },
                        new
                        {
                            Id = new Guid("a014e519-710c-4761-b3e5-e6b3e4b9a830"),
                            Attack = 227,
                            Defense = 341,
                            HealthPoints = 546,
                            KnownFrom = "Rustic Steel Pants",
                            Name = "Alvah",
                            SpecialAttack = 272,
                            SpecialDefense = 403,
                            Speed = 845
                        },
                        new
                        {
                            Id = new Guid("db7ecf6a-a829-4213-9373-e3268bdb5005"),
                            Attack = 464,
                            Defense = 198,
                            HealthPoints = 684,
                            KnownFrom = "Licensed Cotton Ball",
                            Name = "Tiffany",
                            SpecialAttack = 421,
                            SpecialDefense = 261,
                            Speed = 612
                        },
                        new
                        {
                            Id = new Guid("6388835c-e32e-42a8-9102-9b5512bdbb7e"),
                            Attack = 216,
                            Defense = 204,
                            HealthPoints = 447,
                            KnownFrom = "Tasty Metal Tuna",
                            Name = "Pietro",
                            SpecialAttack = 568,
                            SpecialDefense = 571,
                            Speed = 87
                        },
                        new
                        {
                            Id = new Guid("406e54df-3e18-473b-9376-efac2262aceb"),
                            Attack = 89,
                            Defense = 357,
                            HealthPoints = 0,
                            KnownFrom = "Gorgeous Fresh Chicken",
                            Name = "Keshaun",
                            SpecialAttack = 566,
                            SpecialDefense = 61,
                            Speed = 732
                        },
                        new
                        {
                            Id = new Guid("2670328e-4ebe-4569-b1c1-cedaf861ef63"),
                            Attack = 384,
                            Defense = 144,
                            HealthPoints = 497,
                            KnownFrom = "Fantastic Frozen Soap",
                            Name = "Furman",
                            SpecialAttack = 324,
                            SpecialDefense = 228,
                            Speed = 489
                        },
                        new
                        {
                            Id = new Guid("9ab33beb-5b58-423e-91a0-beb52d4f899f"),
                            Attack = 45,
                            Defense = 231,
                            HealthPoints = 193,
                            KnownFrom = "Incredible Metal Pants",
                            Name = "Nicklaus",
                            SpecialAttack = 542,
                            SpecialDefense = 6,
                            Speed = 442
                        },
                        new
                        {
                            Id = new Guid("10b6ea26-b45f-49a9-b71b-64af46e34df5"),
                            Attack = 2,
                            Defense = 620,
                            HealthPoints = 22,
                            KnownFrom = "Unbranded Cotton Chicken",
                            Name = "Bertrand",
                            SpecialAttack = 23,
                            SpecialDefense = 338,
                            Speed = 348
                        },
                        new
                        {
                            Id = new Guid("bcbd6758-49ab-46f4-8e85-fbd1b8e989a9"),
                            Attack = 388,
                            Defense = 129,
                            HealthPoints = 385,
                            KnownFrom = "Incredible Plastic Chicken",
                            Name = "Ian",
                            SpecialAttack = 523,
                            SpecialDefense = 49,
                            Speed = 232
                        },
                        new
                        {
                            Id = new Guid("e90355d6-7127-4a02-bbef-755e58897552"),
                            Attack = 554,
                            Defense = 449,
                            HealthPoints = 186,
                            KnownFrom = "Gorgeous Metal Car",
                            Name = "Kenyon",
                            SpecialAttack = 168,
                            SpecialDefense = 460,
                            Speed = 362
                        },
                        new
                        {
                            Id = new Guid("e3c033d3-c1f5-4def-969b-08e80984a33d"),
                            Attack = 141,
                            Defense = 63,
                            HealthPoints = 66,
                            KnownFrom = "Rustic Plastic Mouse",
                            Name = "Ally",
                            SpecialAttack = 9,
                            SpecialDefense = 16,
                            Speed = 193
                        },
                        new
                        {
                            Id = new Guid("70241048-7fd1-465c-bdbc-76251a62ea8c"),
                            Attack = 706,
                            Defense = 247,
                            HealthPoints = 229,
                            KnownFrom = "Handcrafted Frozen Keyboard",
                            Name = "Emma",
                            SpecialAttack = 72,
                            SpecialDefense = 427,
                            Speed = 352
                        },
                        new
                        {
                            Id = new Guid("84f6c517-d09b-42a2-b102-67b7d3d57c0c"),
                            Attack = 681,
                            Defense = 638,
                            HealthPoints = 654,
                            KnownFrom = "Refined Rubber Bike",
                            Name = "Zelma",
                            SpecialAttack = 224,
                            SpecialDefense = 115,
                            Speed = 271
                        },
                        new
                        {
                            Id = new Guid("6455dca6-931e-45a4-8667-382321d2b884"),
                            Attack = 129,
                            Defense = 602,
                            HealthPoints = 91,
                            KnownFrom = "Unbranded Plastic Chips",
                            Name = "Sammy",
                            SpecialAttack = 370,
                            SpecialDefense = 335,
                            Speed = 364
                        },
                        new
                        {
                            Id = new Guid("2f61ca8c-3c9a-4d0b-915d-08ad7e70e1a9"),
                            Attack = 495,
                            Defense = 236,
                            HealthPoints = 623,
                            KnownFrom = "Intelligent Plastic Shirt",
                            Name = "Adriana",
                            SpecialAttack = 544,
                            SpecialDefense = 17,
                            Speed = 532
                        },
                        new
                        {
                            Id = new Guid("f641afa6-f533-49a2-bbee-f1919316a080"),
                            Attack = 529,
                            Defense = 469,
                            HealthPoints = 707,
                            KnownFrom = "Licensed Cotton Shoes",
                            Name = "June",
                            SpecialAttack = 508,
                            SpecialDefense = 292,
                            Speed = 112
                        },
                        new
                        {
                            Id = new Guid("00abb8df-d769-4a43-aca2-0cbb1b6fa104"),
                            Attack = 589,
                            Defense = 420,
                            HealthPoints = 296,
                            KnownFrom = "Rustic Rubber Towels",
                            Name = "Brain",
                            SpecialAttack = 574,
                            SpecialDefense = 643,
                            Speed = 327
                        },
                        new
                        {
                            Id = new Guid("3fd57887-ec57-414b-945e-2731f82ec813"),
                            Attack = 199,
                            Defense = 549,
                            HealthPoints = 648,
                            KnownFrom = "Tasty Plastic Bike",
                            Name = "Floyd",
                            SpecialAttack = 373,
                            SpecialDefense = 292,
                            Speed = 818
                        },
                        new
                        {
                            Id = new Guid("37365d47-ca47-4027-b540-7384be5ff740"),
                            Attack = 259,
                            Defense = 499,
                            HealthPoints = 141,
                            KnownFrom = "Tasty Soft Tuna",
                            Name = "Eric",
                            SpecialAttack = 133,
                            SpecialDefense = 105,
                            Speed = 516
                        },
                        new
                        {
                            Id = new Guid("375b2145-8f64-4b63-8e1a-b7f5b4d0a97c"),
                            Attack = 539,
                            Defense = 530,
                            HealthPoints = 662,
                            KnownFrom = "Incredible Granite Computer",
                            Name = "Dana",
                            SpecialAttack = 401,
                            SpecialDefense = 278,
                            Speed = 661
                        },
                        new
                        {
                            Id = new Guid("d0e4570c-3576-4bb3-889e-9e3fde36375e"),
                            Attack = 284,
                            Defense = 15,
                            HealthPoints = 602,
                            KnownFrom = "Gorgeous Rubber Soap",
                            Name = "Leon",
                            SpecialAttack = 100,
                            SpecialDefense = 129,
                            Speed = 198
                        },
                        new
                        {
                            Id = new Guid("ee152b7e-c961-41fb-a242-ae865586e3b1"),
                            Attack = 206,
                            Defense = 331,
                            HealthPoints = 516,
                            KnownFrom = "Awesome Metal Shoes",
                            Name = "Declan",
                            SpecialAttack = 521,
                            SpecialDefense = 517,
                            Speed = 740
                        },
                        new
                        {
                            Id = new Guid("94156dd6-9533-4274-8a9f-3fe26c0fe44a"),
                            Attack = 216,
                            Defense = 138,
                            HealthPoints = 647,
                            KnownFrom = "Awesome Fresh Table",
                            Name = "Eduardo",
                            SpecialAttack = 88,
                            SpecialDefense = 276,
                            Speed = 494
                        },
                        new
                        {
                            Id = new Guid("ead6ff21-2953-4a47-ac83-c05aac20609c"),
                            Attack = 323,
                            Defense = 451,
                            HealthPoints = 81,
                            KnownFrom = "Unbranded Concrete Fish",
                            Name = "Dane",
                            SpecialAttack = 419,
                            SpecialDefense = 198,
                            Speed = 767
                        },
                        new
                        {
                            Id = new Guid("64a21261-5795-49f1-8bf4-13539f9b90d3"),
                            Attack = 189,
                            Defense = 375,
                            HealthPoints = 33,
                            KnownFrom = "Ergonomic Fresh Pants",
                            Name = "Cleveland",
                            SpecialAttack = 159,
                            SpecialDefense = 117,
                            Speed = 367
                        },
                        new
                        {
                            Id = new Guid("e262c294-a557-46b7-acd8-e32d669b6ac7"),
                            Attack = 135,
                            Defense = 73,
                            HealthPoints = 22,
                            KnownFrom = "Refined Steel Car",
                            Name = "Annette",
                            SpecialAttack = 608,
                            SpecialDefense = 622,
                            Speed = 252
                        },
                        new
                        {
                            Id = new Guid("62a4990a-344e-4d30-b44c-3fa827d489a5"),
                            Attack = 694,
                            Defense = 384,
                            HealthPoints = 71,
                            KnownFrom = "Generic Rubber Chicken",
                            Name = "Cheyenne",
                            SpecialAttack = 591,
                            SpecialDefense = 506,
                            Speed = 254
                        },
                        new
                        {
                            Id = new Guid("c574d7ad-911a-4a86-84be-7b3e3725ca15"),
                            Attack = 415,
                            Defense = 170,
                            HealthPoints = 299,
                            KnownFrom = "Incredible Fresh Hat",
                            Name = "Keyon",
                            SpecialAttack = 369,
                            SpecialDefense = 465,
                            Speed = 389
                        },
                        new
                        {
                            Id = new Guid("a07df502-8907-4375-97f4-5e5b85213118"),
                            Attack = 330,
                            Defense = 460,
                            HealthPoints = 193,
                            KnownFrom = "Intelligent Steel Car",
                            Name = "Reilly",
                            SpecialAttack = 273,
                            SpecialDefense = 214,
                            Speed = 604
                        },
                        new
                        {
                            Id = new Guid("f10eea79-7948-4922-a0fb-61e29a02f27f"),
                            Attack = 367,
                            Defense = 510,
                            HealthPoints = 395,
                            KnownFrom = "Handcrafted Metal Cheese",
                            Name = "Dixie",
                            SpecialAttack = 211,
                            SpecialDefense = 114,
                            Speed = 805
                        },
                        new
                        {
                            Id = new Guid("fb52b819-1875-44e2-930a-7dc89704759c"),
                            Attack = 507,
                            Defense = 636,
                            HealthPoints = 654,
                            KnownFrom = "Sleek Granite Chair",
                            Name = "Johann",
                            SpecialAttack = 341,
                            SpecialDefense = 205,
                            Speed = 405
                        },
                        new
                        {
                            Id = new Guid("c083445b-0563-487f-9476-15347c509887"),
                            Attack = 558,
                            Defense = 66,
                            HealthPoints = 3,
                            KnownFrom = "Licensed Cotton Shoes",
                            Name = "Emery",
                            SpecialAttack = 475,
                            SpecialDefense = 390,
                            Speed = 724
                        },
                        new
                        {
                            Id = new Guid("797f95ca-b683-4db6-9df7-2633d8cd2a4b"),
                            Attack = 529,
                            Defense = 165,
                            HealthPoints = 119,
                            KnownFrom = "Tasty Steel Chips",
                            Name = "Rae",
                            SpecialAttack = 513,
                            SpecialDefense = 150,
                            Speed = 715
                        },
                        new
                        {
                            Id = new Guid("548750ba-7901-43f7-b579-86b18c2b793d"),
                            Attack = 527,
                            Defense = 283,
                            HealthPoints = 411,
                            KnownFrom = "Generic Granite Salad",
                            Name = "Scottie",
                            SpecialAttack = 25,
                            SpecialDefense = 323,
                            Speed = 357
                        },
                        new
                        {
                            Id = new Guid("a959eee9-6022-482c-af42-87f24ace4053"),
                            Attack = 203,
                            Defense = 363,
                            HealthPoints = 151,
                            KnownFrom = "Awesome Steel Pizza",
                            Name = "Krystal",
                            SpecialAttack = 8,
                            SpecialDefense = 535,
                            Speed = 289
                        },
                        new
                        {
                            Id = new Guid("1fc91f98-0b97-4dcc-9c7c-8b5a50dcc9fa"),
                            Attack = 460,
                            Defense = 475,
                            HealthPoints = 67,
                            KnownFrom = "Handcrafted Metal Fish",
                            Name = "Enrico",
                            SpecialAttack = 491,
                            SpecialDefense = 225,
                            Speed = 113
                        },
                        new
                        {
                            Id = new Guid("8d649662-1aaf-4cd4-a97a-4a29e08686ab"),
                            Attack = 150,
                            Defense = 605,
                            HealthPoints = 653,
                            KnownFrom = "Ergonomic Wooden Soap",
                            Name = "Jorge",
                            SpecialAttack = 22,
                            SpecialDefense = 94,
                            Speed = 478
                        },
                        new
                        {
                            Id = new Guid("9825db62-e2eb-4dd4-8a2e-b3838f481250"),
                            Attack = 316,
                            Defense = 466,
                            HealthPoints = 687,
                            KnownFrom = "Gorgeous Steel Car",
                            Name = "Antonia",
                            SpecialAttack = 444,
                            SpecialDefense = 512,
                            Speed = 369
                        },
                        new
                        {
                            Id = new Guid("75bef2b3-aca1-4daa-b720-0095a8080b59"),
                            Attack = 124,
                            Defense = 238,
                            HealthPoints = 244,
                            KnownFrom = "Refined Rubber Chips",
                            Name = "Freida",
                            SpecialAttack = 495,
                            SpecialDefense = 40,
                            Speed = 385
                        },
                        new
                        {
                            Id = new Guid("9117e36a-4492-41e6-a3a7-5289278517f0"),
                            Attack = 517,
                            Defense = 120,
                            HealthPoints = 406,
                            KnownFrom = "Tasty Steel Sausages",
                            Name = "Neal",
                            SpecialAttack = 225,
                            SpecialDefense = 13,
                            Speed = 33
                        },
                        new
                        {
                            Id = new Guid("39a7728a-cef0-408e-be8f-737e53c07b14"),
                            Attack = 7,
                            Defense = 482,
                            HealthPoints = 242,
                            KnownFrom = "Unbranded Plastic Chair",
                            Name = "Bulah",
                            SpecialAttack = 57,
                            SpecialDefense = 639,
                            Speed = 742
                        },
                        new
                        {
                            Id = new Guid("bacdc38d-c6d5-45f3-919d-9e838e27cfdb"),
                            Attack = 399,
                            Defense = 461,
                            HealthPoints = 377,
                            KnownFrom = "Unbranded Cotton Soap",
                            Name = "Nakia",
                            SpecialAttack = 299,
                            SpecialDefense = 334,
                            Speed = 774
                        },
                        new
                        {
                            Id = new Guid("f837ddd9-ec72-4569-b061-017e7ec2af0b"),
                            Attack = 704,
                            Defense = 126,
                            HealthPoints = 112,
                            KnownFrom = "Practical Granite Tuna",
                            Name = "Brent",
                            SpecialAttack = 577,
                            SpecialDefense = 396,
                            Speed = 237
                        },
                        new
                        {
                            Id = new Guid("0927d600-0d64-43d8-a044-2963ab7f5c51"),
                            Attack = 554,
                            Defense = 96,
                            HealthPoints = 98,
                            KnownFrom = "Gorgeous Soft Mouse",
                            Name = "Ines",
                            SpecialAttack = 296,
                            SpecialDefense = 215,
                            Speed = 225
                        },
                        new
                        {
                            Id = new Guid("9ba64ea9-12fc-421f-a087-a6d2dc4b3a71"),
                            Attack = 687,
                            Defense = 163,
                            HealthPoints = 278,
                            KnownFrom = "Intelligent Fresh Tuna",
                            Name = "Vincenza",
                            SpecialAttack = 492,
                            SpecialDefense = 453,
                            Speed = 488
                        },
                        new
                        {
                            Id = new Guid("45fcf42a-9929-4266-a843-9ca42d78d16f"),
                            Attack = 395,
                            Defense = 317,
                            HealthPoints = 94,
                            KnownFrom = "Incredible Metal Car",
                            Name = "Michele",
                            SpecialAttack = 470,
                            SpecialDefense = 379,
                            Speed = 840
                        },
                        new
                        {
                            Id = new Guid("1cb3d99a-3942-4f92-92f3-d7cd0c37f18f"),
                            Attack = 117,
                            Defense = 475,
                            HealthPoints = 82,
                            KnownFrom = "Awesome Granite Gloves",
                            Name = "Antonio",
                            SpecialAttack = 518,
                            SpecialDefense = 190,
                            Speed = 774
                        },
                        new
                        {
                            Id = new Guid("e9c8b1d2-e257-4a1c-8eac-d2698cffa113"),
                            Attack = 679,
                            Defense = 352,
                            HealthPoints = 253,
                            KnownFrom = "Handmade Fresh Chips",
                            Name = "Agustin",
                            SpecialAttack = 332,
                            SpecialDefense = 647,
                            Speed = 159
                        },
                        new
                        {
                            Id = new Guid("2af195a2-2fba-4bad-8add-c50b98901668"),
                            Attack = 721,
                            Defense = 159,
                            HealthPoints = 48,
                            KnownFrom = "Unbranded Wooden Bacon",
                            Name = "Willie",
                            SpecialAttack = 551,
                            SpecialDefense = 229,
                            Speed = 519
                        },
                        new
                        {
                            Id = new Guid("63491d0d-7b79-4e64-aff7-345377cf1cde"),
                            Attack = 538,
                            Defense = 446,
                            HealthPoints = 422,
                            KnownFrom = "Fantastic Wooden Shirt",
                            Name = "Laron",
                            SpecialAttack = 108,
                            SpecialDefense = 475,
                            Speed = 248
                        },
                        new
                        {
                            Id = new Guid("c6dece1e-1b3f-4d2f-bde6-1f15cbe7b079"),
                            Attack = 702,
                            Defense = 533,
                            HealthPoints = 395,
                            KnownFrom = "Tasty Concrete Chair",
                            Name = "Felipe",
                            SpecialAttack = 97,
                            SpecialDefense = 641,
                            Speed = 742
                        },
                        new
                        {
                            Id = new Guid("84744404-4196-4ddd-ba66-fd2f052b9225"),
                            Attack = 279,
                            Defense = 261,
                            HealthPoints = 62,
                            KnownFrom = "Incredible Soft Gloves",
                            Name = "Ebony",
                            SpecialAttack = 63,
                            SpecialDefense = 416,
                            Speed = 207
                        },
                        new
                        {
                            Id = new Guid("608e767a-23a4-469c-b478-4e08f4c1abc5"),
                            Attack = 569,
                            Defense = 387,
                            HealthPoints = 157,
                            KnownFrom = "Ergonomic Plastic Shirt",
                            Name = "Viola",
                            SpecialAttack = 84,
                            SpecialDefense = 99,
                            Speed = 492
                        },
                        new
                        {
                            Id = new Guid("fcefc4dd-dbf8-423b-a681-a03b4543f1d5"),
                            Attack = 680,
                            Defense = 84,
                            HealthPoints = 374,
                            KnownFrom = "Handcrafted Wooden Chicken",
                            Name = "Hailey",
                            SpecialAttack = 260,
                            SpecialDefense = 350,
                            Speed = 800
                        },
                        new
                        {
                            Id = new Guid("5653e460-1d0f-4f1e-8b70-14e75d899022"),
                            Attack = 573,
                            Defense = 111,
                            HealthPoints = 174,
                            KnownFrom = "Handcrafted Cotton Hat",
                            Name = "Rod",
                            SpecialAttack = 550,
                            SpecialDefense = 397,
                            Speed = 544
                        },
                        new
                        {
                            Id = new Guid("e168e4e0-99bb-442e-8d1d-8cabe324ecba"),
                            Attack = 499,
                            Defense = 275,
                            HealthPoints = 241,
                            KnownFrom = "Licensed Soft Bike",
                            Name = "Mike",
                            SpecialAttack = 395,
                            SpecialDefense = 106,
                            Speed = 409
                        },
                        new
                        {
                            Id = new Guid("ab2da342-78e1-4aa6-bedd-074d55b18e68"),
                            Attack = 428,
                            Defense = 355,
                            HealthPoints = 121,
                            KnownFrom = "Refined Granite Bike",
                            Name = "Rashawn",
                            SpecialAttack = 386,
                            SpecialDefense = 469,
                            Speed = 126
                        },
                        new
                        {
                            Id = new Guid("a881e684-0b4f-45bf-8d70-db6233b3fc97"),
                            Attack = 342,
                            Defense = 2,
                            HealthPoints = 66,
                            KnownFrom = "Rustic Wooden Gloves",
                            Name = "Ettie",
                            SpecialAttack = 367,
                            SpecialDefense = 24,
                            Speed = 376
                        },
                        new
                        {
                            Id = new Guid("8b7691f3-ad5c-4bbe-aacc-4d3b72bc6362"),
                            Attack = 155,
                            Defense = 487,
                            HealthPoints = 147,
                            KnownFrom = "Handcrafted Frozen Salad",
                            Name = "Mohamed",
                            SpecialAttack = 569,
                            SpecialDefense = 225,
                            Speed = 448
                        },
                        new
                        {
                            Id = new Guid("16a4cb7b-5da5-428c-89bb-eb0f8c3236a2"),
                            Attack = 36,
                            Defense = 583,
                            HealthPoints = 107,
                            KnownFrom = "Handmade Plastic Keyboard",
                            Name = "Wilburn",
                            SpecialAttack = 217,
                            SpecialDefense = 236,
                            Speed = 528
                        },
                        new
                        {
                            Id = new Guid("0bc3f7c6-a582-44bd-8c58-58a03536c85e"),
                            Attack = 404,
                            Defense = 496,
                            HealthPoints = 429,
                            KnownFrom = "Handmade Granite Ball",
                            Name = "Barrett",
                            SpecialAttack = 570,
                            SpecialDefense = 247,
                            Speed = 732
                        },
                        new
                        {
                            Id = new Guid("0be361ac-4806-4bda-98cc-f4129847da52"),
                            Attack = 166,
                            Defense = 146,
                            HealthPoints = 499,
                            KnownFrom = "Intelligent Concrete Keyboard",
                            Name = "Victor",
                            SpecialAttack = 170,
                            SpecialDefense = 171,
                            Speed = 163
                        },
                        new
                        {
                            Id = new Guid("b56957b1-3579-4b73-9911-205779049fa2"),
                            Attack = 250,
                            Defense = 571,
                            HealthPoints = 363,
                            KnownFrom = "Sleek Frozen Tuna",
                            Name = "Jaleel",
                            SpecialAttack = 302,
                            SpecialDefense = 575,
                            Speed = 757
                        },
                        new
                        {
                            Id = new Guid("195801a5-c8c9-45dd-bcee-2a18fc3aefce"),
                            Attack = 105,
                            Defense = 122,
                            HealthPoints = 694,
                            KnownFrom = "Tasty Fresh Bike",
                            Name = "Haley",
                            SpecialAttack = 458,
                            SpecialDefense = 561,
                            Speed = 476
                        },
                        new
                        {
                            Id = new Guid("6806c850-8be1-44ca-8c36-d069ef28e6b5"),
                            Attack = 596,
                            Defense = 84,
                            HealthPoints = 424,
                            KnownFrom = "Generic Wooden Gloves",
                            Name = "Valentina",
                            SpecialAttack = 603,
                            SpecialDefense = 172,
                            Speed = 235
                        },
                        new
                        {
                            Id = new Guid("0b8e85d9-84d9-48ad-9ec5-7f6091d45ceb"),
                            Attack = 532,
                            Defense = 548,
                            HealthPoints = 58,
                            KnownFrom = "Gorgeous Concrete Tuna",
                            Name = "Rey",
                            SpecialAttack = 350,
                            SpecialDefense = 416,
                            Speed = 410
                        },
                        new
                        {
                            Id = new Guid("c1c56375-d838-4279-9bbf-88a788bf3379"),
                            Attack = 223,
                            Defense = 308,
                            HealthPoints = 280,
                            KnownFrom = "Ergonomic Concrete Hat",
                            Name = "Felton",
                            SpecialAttack = 34,
                            SpecialDefense = 304,
                            Speed = 673
                        },
                        new
                        {
                            Id = new Guid("5365d73b-6c32-4d68-b9a5-ddaebb01d832"),
                            Attack = 200,
                            Defense = 76,
                            HealthPoints = 19,
                            KnownFrom = "Refined Steel Tuna",
                            Name = "Trenton",
                            SpecialAttack = 231,
                            SpecialDefense = 255,
                            Speed = 641
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
