// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyMon_Blazor.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonkeyMon_Blazor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241106152002_Species")]
    partial class Species
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Monkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Attack")
                        .HasColumnType("integer");

                    b.Property<int?>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<string>("KnownFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialDefense")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Monkeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2a343e4-d6d5-44d4-9a05-772eb12d11bc"),
                            Attack = 489,
                            Defense = 411,
                            HealthPoints = 391,
                            KnownFrom = "Handcrafted Frozen Bacon",
                            Name = "Bernice",
                            SpecialAttack = 558,
                            SpecialDefense = 87,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 449
                        },
                        new
                        {
                            Id = new Guid("d5ab21ce-59d5-4419-99d3-f13f4a310af1"),
                            Attack = 557,
                            Defense = 188,
                            HealthPoints = 5,
                            KnownFrom = "Awesome Metal Shirt",
                            Name = "Elisha",
                            SpecialAttack = 100,
                            SpecialDefense = 127,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 814
                        },
                        new
                        {
                            Id = new Guid("137bd13a-ca91-43b0-8125-3bb4c4bc01f3"),
                            Attack = 297,
                            Defense = 362,
                            HealthPoints = 436,
                            KnownFrom = "Refined Steel Chicken",
                            Name = "Laron",
                            SpecialAttack = 526,
                            SpecialDefense = 440,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 819
                        },
                        new
                        {
                            Id = new Guid("64032793-92da-471b-8fef-3d0a0ab4d6ae"),
                            Attack = 557,
                            Defense = 90,
                            HealthPoints = 384,
                            KnownFrom = "Small Concrete Fish",
                            Name = "Alene",
                            SpecialAttack = 195,
                            SpecialDefense = 186,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 324
                        },
                        new
                        {
                            Id = new Guid("ffc7e58c-ce2f-43ee-8622-fd0bc28f7dbe"),
                            Attack = 402,
                            Defense = 167,
                            HealthPoints = 40,
                            KnownFrom = "Generic Cotton Chips",
                            Name = "Sophia",
                            SpecialAttack = 457,
                            SpecialDefense = 627,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 567
                        },
                        new
                        {
                            Id = new Guid("af866876-a6d5-4e01-b981-a5174b0b144b"),
                            Attack = 457,
                            Defense = 571,
                            HealthPoints = 34,
                            KnownFrom = "Intelligent Frozen Chips",
                            Name = "Foster",
                            SpecialAttack = 13,
                            SpecialDefense = 156,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 150
                        },
                        new
                        {
                            Id = new Guid("07d3dc32-e73d-4629-85e7-fa31d6a4b86a"),
                            Attack = 682,
                            Defense = 619,
                            HealthPoints = 703,
                            KnownFrom = "Fantastic Plastic Chips",
                            Name = "Celia",
                            SpecialAttack = 333,
                            SpecialDefense = 79,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 542
                        },
                        new
                        {
                            Id = new Guid("c4b95468-3646-424f-9ed4-f62791bcaa86"),
                            Attack = 387,
                            Defense = 442,
                            HealthPoints = 481,
                            KnownFrom = "Tasty Concrete Salad",
                            Name = "Westley",
                            SpecialAttack = 483,
                            SpecialDefense = 28,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 372
                        },
                        new
                        {
                            Id = new Guid("2075688d-0317-41e8-82f7-1a15b8241586"),
                            Attack = 141,
                            Defense = 128,
                            HealthPoints = 96,
                            KnownFrom = "Practical Granite Soap",
                            Name = "Carolyn",
                            SpecialAttack = 308,
                            SpecialDefense = 77,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 571
                        },
                        new
                        {
                            Id = new Guid("6634dc37-11b4-4039-a0cb-14a4bf011254"),
                            Attack = 375,
                            Defense = 489,
                            HealthPoints = 496,
                            KnownFrom = "Licensed Fresh Mouse",
                            Name = "Emory",
                            SpecialAttack = 328,
                            SpecialDefense = 374,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 689
                        },
                        new
                        {
                            Id = new Guid("f22f0caa-28e6-4bfd-8942-66eb85e176bc"),
                            Attack = 364,
                            Defense = 632,
                            HealthPoints = 287,
                            KnownFrom = "Small Fresh Pizza",
                            Name = "Katelynn",
                            SpecialAttack = 22,
                            SpecialDefense = 117,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 517
                        },
                        new
                        {
                            Id = new Guid("9cd4e581-c513-4775-b3c2-f9b72532bd3f"),
                            Attack = 104,
                            Defense = 161,
                            HealthPoints = 101,
                            KnownFrom = "Awesome Rubber Shirt",
                            Name = "Jacynthe",
                            SpecialAttack = 358,
                            SpecialDefense = 45,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 719
                        },
                        new
                        {
                            Id = new Guid("897e5f82-d9d3-4450-890b-b2ee4b5f312a"),
                            Attack = 517,
                            Defense = 485,
                            HealthPoints = 468,
                            KnownFrom = "Practical Wooden Salad",
                            Name = "Layla",
                            SpecialAttack = 457,
                            SpecialDefense = 535,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 558
                        },
                        new
                        {
                            Id = new Guid("74d1aa89-d813-4640-908a-6ef5e6fbfcab"),
                            Attack = 631,
                            Defense = 403,
                            HealthPoints = 290,
                            KnownFrom = "Refined Concrete Computer",
                            Name = "Lonzo",
                            SpecialAttack = 414,
                            SpecialDefense = 319,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 310
                        },
                        new
                        {
                            Id = new Guid("5ff2a1aa-d576-4144-8ee2-256570c2e797"),
                            Attack = 167,
                            Defense = 380,
                            HealthPoints = 203,
                            KnownFrom = "Generic Granite Chips",
                            Name = "Evangeline",
                            SpecialAttack = 266,
                            SpecialDefense = 8,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 245
                        },
                        new
                        {
                            Id = new Guid("38a15a2d-f39b-4c82-8da1-af43e4325356"),
                            Attack = 131,
                            Defense = 186,
                            HealthPoints = 503,
                            KnownFrom = "Practical Frozen Keyboard",
                            Name = "Hester",
                            SpecialAttack = 321,
                            SpecialDefense = 426,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 682
                        },
                        new
                        {
                            Id = new Guid("4248f718-5db1-48f3-9390-fc8bb64aa972"),
                            Attack = 335,
                            Defense = 423,
                            HealthPoints = 595,
                            KnownFrom = "Generic Cotton Bike",
                            Name = "Lorenzo",
                            SpecialAttack = 284,
                            SpecialDefense = 75,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 529
                        },
                        new
                        {
                            Id = new Guid("e0f84018-0b4c-4313-9e9b-82b94af0261b"),
                            Attack = 253,
                            Defense = 325,
                            HealthPoints = 67,
                            KnownFrom = "Ergonomic Wooden Car",
                            Name = "Franz",
                            SpecialAttack = 307,
                            SpecialDefense = 52,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 681
                        },
                        new
                        {
                            Id = new Guid("3394dfa5-cdea-4e4c-8f52-ec69909d26b6"),
                            Attack = 17,
                            Defense = 218,
                            HealthPoints = 547,
                            KnownFrom = "Gorgeous Plastic Keyboard",
                            Name = "Quentin",
                            SpecialAttack = 568,
                            SpecialDefense = 621,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 114
                        },
                        new
                        {
                            Id = new Guid("39c7ca0b-0341-44be-b166-ebcdcadab23a"),
                            Attack = 523,
                            Defense = 503,
                            HealthPoints = 22,
                            KnownFrom = "Ergonomic Fresh Car",
                            Name = "Julianne",
                            SpecialAttack = 555,
                            SpecialDefense = 154,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 189
                        },
                        new
                        {
                            Id = new Guid("bb1abeae-2017-445d-9f75-134d1be5f7aa"),
                            Attack = 604,
                            Defense = 411,
                            HealthPoints = 619,
                            KnownFrom = "Generic Rubber Hat",
                            Name = "Uriel",
                            SpecialAttack = 286,
                            SpecialDefense = 410,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 556
                        },
                        new
                        {
                            Id = new Guid("dd938f44-1084-4949-af6a-90e9823a84ea"),
                            Attack = 86,
                            Defense = 85,
                            HealthPoints = 150,
                            KnownFrom = "Generic Frozen Towels",
                            Name = "Evalyn",
                            SpecialAttack = 198,
                            SpecialDefense = 200,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 158
                        },
                        new
                        {
                            Id = new Guid("a041c6e1-61ee-45aa-b444-a60b105f53e2"),
                            Attack = 402,
                            Defense = 641,
                            HealthPoints = 165,
                            KnownFrom = "Intelligent Concrete Chips",
                            Name = "Griffin",
                            SpecialAttack = 347,
                            SpecialDefense = 403,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 501
                        },
                        new
                        {
                            Id = new Guid("e27c7c13-6a26-40d3-9b1a-9fd2398b4185"),
                            Attack = 77,
                            Defense = 115,
                            HealthPoints = 399,
                            KnownFrom = "Handmade Fresh Car",
                            Name = "Adolfo",
                            SpecialAttack = 593,
                            SpecialDefense = 542,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 362
                        },
                        new
                        {
                            Id = new Guid("fae791c9-5fad-4469-8203-668b06187868"),
                            Attack = 212,
                            Defense = 309,
                            HealthPoints = 308,
                            KnownFrom = "Handmade Steel Computer",
                            Name = "Cyril",
                            SpecialAttack = 387,
                            SpecialDefense = 584,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 593
                        },
                        new
                        {
                            Id = new Guid("a4f29555-3f29-4dd6-a708-a0a02ba72c59"),
                            Attack = 676,
                            Defense = 373,
                            HealthPoints = 639,
                            KnownFrom = "Gorgeous Fresh Bike",
                            Name = "Kelli",
                            SpecialAttack = 424,
                            SpecialDefense = 465,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 397
                        },
                        new
                        {
                            Id = new Guid("09f879c8-fe67-4ed2-9ddb-5fef1f4ca8e6"),
                            Attack = 119,
                            Defense = 163,
                            HealthPoints = 572,
                            KnownFrom = "Handcrafted Plastic Fish",
                            Name = "Kristian",
                            SpecialAttack = 516,
                            SpecialDefense = 302,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 71
                        },
                        new
                        {
                            Id = new Guid("45336c6e-8524-49ca-9612-14353fb60b15"),
                            Attack = 457,
                            Defense = 561,
                            HealthPoints = 494,
                            KnownFrom = "Fantastic Wooden Sausages",
                            Name = "Edison",
                            SpecialAttack = 46,
                            SpecialDefense = 554,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 169
                        },
                        new
                        {
                            Id = new Guid("d5c07087-dedf-4e34-92f7-b49f3ca5106e"),
                            Attack = 128,
                            Defense = 410,
                            HealthPoints = 385,
                            KnownFrom = "Ergonomic Cotton Gloves",
                            Name = "Kristy",
                            SpecialAttack = 162,
                            SpecialDefense = 442,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 284
                        },
                        new
                        {
                            Id = new Guid("627e639f-e18c-42a0-9e6e-f95c34766795"),
                            Attack = 486,
                            Defense = 596,
                            HealthPoints = 431,
                            KnownFrom = "Licensed Rubber Table",
                            Name = "Samara",
                            SpecialAttack = 33,
                            SpecialDefense = 460,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 424
                        },
                        new
                        {
                            Id = new Guid("3eed2cb2-f011-4b51-aadf-5d220fc29776"),
                            Attack = 585,
                            Defense = 214,
                            HealthPoints = 178,
                            KnownFrom = "Ergonomic Fresh Car",
                            Name = "Eldridge",
                            SpecialAttack = 126,
                            SpecialDefense = 527,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 151
                        },
                        new
                        {
                            Id = new Guid("7a8b4188-503a-493e-a147-1b3159c6d650"),
                            Attack = 157,
                            Defense = 322,
                            HealthPoints = 621,
                            KnownFrom = "Gorgeous Fresh Hat",
                            Name = "Dave",
                            SpecialAttack = 341,
                            SpecialDefense = 564,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 78
                        },
                        new
                        {
                            Id = new Guid("95d08833-3a41-4182-9714-d80f9e31eae3"),
                            Attack = 631,
                            Defense = 355,
                            HealthPoints = 201,
                            KnownFrom = "Small Fresh Chips",
                            Name = "Glen",
                            SpecialAttack = 337,
                            SpecialDefense = 188,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 741
                        },
                        new
                        {
                            Id = new Guid("fb81b826-cc2b-499d-a292-702fb3dc8820"),
                            Attack = 19,
                            Defense = 215,
                            HealthPoints = 698,
                            KnownFrom = "Incredible Granite Sausages",
                            Name = "Abigayle",
                            SpecialAttack = 324,
                            SpecialDefense = 341,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 567
                        },
                        new
                        {
                            Id = new Guid("95242b39-4e00-4079-b5f2-7c4a598ce33c"),
                            Attack = 395,
                            Defense = 117,
                            HealthPoints = 570,
                            KnownFrom = "Rustic Wooden Chips",
                            Name = "Luella",
                            SpecialAttack = 174,
                            SpecialDefense = 67,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 162
                        },
                        new
                        {
                            Id = new Guid("aa8f9e61-861f-4ec9-93da-3754edd117b2"),
                            Attack = 101,
                            Defense = 191,
                            HealthPoints = 542,
                            KnownFrom = "Gorgeous Wooden Table",
                            Name = "Bryana",
                            SpecialAttack = 1,
                            SpecialDefense = 424,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 45
                        },
                        new
                        {
                            Id = new Guid("d980f17a-7a1f-4da1-b331-12bd7562c264"),
                            Attack = 97,
                            Defense = 10,
                            HealthPoints = 654,
                            KnownFrom = "Licensed Frozen Mouse",
                            Name = "Reva",
                            SpecialAttack = 203,
                            SpecialDefense = 462,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 347
                        },
                        new
                        {
                            Id = new Guid("08d359dd-a8c1-4000-9305-0d8caa3946b4"),
                            Attack = 208,
                            Defense = 507,
                            HealthPoints = 6,
                            KnownFrom = "Ergonomic Concrete Car",
                            Name = "Christop",
                            SpecialAttack = 181,
                            SpecialDefense = 30,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 244
                        },
                        new
                        {
                            Id = new Guid("44c8199e-da3a-4ee0-9db3-ebe4d4ba4e56"),
                            Attack = 487,
                            Defense = 74,
                            HealthPoints = 92,
                            KnownFrom = "Rustic Soft Cheese",
                            Name = "Darron",
                            SpecialAttack = 349,
                            SpecialDefense = 232,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 434
                        },
                        new
                        {
                            Id = new Guid("ce3c5df8-ad75-4565-acc8-12a41e0e8b56"),
                            Attack = 284,
                            Defense = 95,
                            HealthPoints = 103,
                            KnownFrom = "Tasty Rubber Keyboard",
                            Name = "Lilliana",
                            SpecialAttack = 570,
                            SpecialDefense = 455,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 412
                        },
                        new
                        {
                            Id = new Guid("7f4553f2-8020-472d-9379-48b1dc647df3"),
                            Attack = 511,
                            Defense = 302,
                            HealthPoints = 23,
                            KnownFrom = "Rustic Fresh Salad",
                            Name = "Jedediah",
                            SpecialAttack = 326,
                            SpecialDefense = 253,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 356
                        },
                        new
                        {
                            Id = new Guid("5a2c91d5-ad00-4916-bec8-c3e6537e60ea"),
                            Attack = 255,
                            Defense = 570,
                            HealthPoints = 382,
                            KnownFrom = "Rustic Metal Gloves",
                            Name = "Gerda",
                            SpecialAttack = 13,
                            SpecialDefense = 101,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 196
                        },
                        new
                        {
                            Id = new Guid("be4b1170-e314-463c-afc3-700e2adc85a1"),
                            Attack = 141,
                            Defense = 106,
                            HealthPoints = 379,
                            KnownFrom = "Licensed Granite Bacon",
                            Name = "Alexie",
                            SpecialAttack = 40,
                            SpecialDefense = 495,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 390
                        },
                        new
                        {
                            Id = new Guid("11511a2b-d305-49c0-9a0d-f8d8c40957ca"),
                            Attack = 211,
                            Defense = 174,
                            HealthPoints = 679,
                            KnownFrom = "Gorgeous Concrete Keyboard",
                            Name = "Janelle",
                            SpecialAttack = 20,
                            SpecialDefense = 402,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 74
                        },
                        new
                        {
                            Id = new Guid("5f3cce4f-c51f-43fe-8963-5af7c8dab361"),
                            Attack = 150,
                            Defense = 624,
                            HealthPoints = 146,
                            KnownFrom = "Rustic Frozen Salad",
                            Name = "Prudence",
                            SpecialAttack = 72,
                            SpecialDefense = 203,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 633
                        },
                        new
                        {
                            Id = new Guid("d8004d44-9783-44f5-b1ba-3b6a4fffa427"),
                            Attack = 220,
                            Defense = 160,
                            HealthPoints = 94,
                            KnownFrom = "Unbranded Plastic Mouse",
                            Name = "Jody",
                            SpecialAttack = 92,
                            SpecialDefense = 279,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 364
                        },
                        new
                        {
                            Id = new Guid("46f889f2-1de2-480d-b09d-3a7a8b40415a"),
                            Attack = 663,
                            Defense = 448,
                            HealthPoints = 533,
                            KnownFrom = "Tasty Plastic Computer",
                            Name = "Simeon",
                            SpecialAttack = 131,
                            SpecialDefense = 42,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 407
                        },
                        new
                        {
                            Id = new Guid("a895728f-ef73-436d-a83d-ab7215d161ae"),
                            Attack = 528,
                            Defense = 292,
                            HealthPoints = 374,
                            KnownFrom = "Practical Fresh Tuna",
                            Name = "Alfreda",
                            SpecialAttack = 282,
                            SpecialDefense = 51,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 97
                        },
                        new
                        {
                            Id = new Guid("da31906a-61cf-4c83-af6f-f67934c0ded6"),
                            Attack = 246,
                            Defense = 282,
                            HealthPoints = 322,
                            KnownFrom = "Practical Frozen Shoes",
                            Name = "Jan",
                            SpecialAttack = 223,
                            SpecialDefense = 630,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 676
                        },
                        new
                        {
                            Id = new Guid("7032e29d-70c6-455a-91c9-0295d0e7b28e"),
                            Attack = 367,
                            Defense = 501,
                            HealthPoints = 490,
                            KnownFrom = "Gorgeous Granite Keyboard",
                            Name = "Odell",
                            SpecialAttack = 473,
                            SpecialDefense = 554,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 669
                        },
                        new
                        {
                            Id = new Guid("d09ea5bf-1e86-4039-9c22-ad3f75998964"),
                            Attack = 689,
                            Defense = 215,
                            HealthPoints = 227,
                            KnownFrom = "Handmade Frozen Gloves",
                            Name = "Silas",
                            SpecialAttack = 285,
                            SpecialDefense = 250,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 387
                        },
                        new
                        {
                            Id = new Guid("258248d5-9ba3-4ea0-8c32-ee98f0eb759d"),
                            Attack = 313,
                            Defense = 555,
                            HealthPoints = 129,
                            KnownFrom = "Intelligent Soft Car",
                            Name = "Monique",
                            SpecialAttack = 526,
                            SpecialDefense = 484,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 207
                        },
                        new
                        {
                            Id = new Guid("1bc59771-4c6d-493b-a448-e7a56ce1dcaa"),
                            Attack = 353,
                            Defense = 322,
                            HealthPoints = 88,
                            KnownFrom = "Generic Concrete Bike",
                            Name = "Hilda",
                            SpecialAttack = 177,
                            SpecialDefense = 125,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 367
                        },
                        new
                        {
                            Id = new Guid("7026e0f7-7784-47e6-ba52-a8202a8f04a5"),
                            Attack = 84,
                            Defense = 471,
                            HealthPoints = 253,
                            KnownFrom = "Refined Metal Table",
                            Name = "Sabrina",
                            SpecialAttack = 24,
                            SpecialDefense = 564,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 813
                        },
                        new
                        {
                            Id = new Guid("a80853de-8577-4ef2-a354-9b554f918afd"),
                            Attack = 680,
                            Defense = 218,
                            HealthPoints = 337,
                            KnownFrom = "Small Frozen Fish",
                            Name = "Consuelo",
                            SpecialAttack = 429,
                            SpecialDefense = 507,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 233
                        },
                        new
                        {
                            Id = new Guid("0023c9ff-1195-402e-ab91-7ece62861f9c"),
                            Attack = 113,
                            Defense = 441,
                            HealthPoints = 483,
                            KnownFrom = "Fantastic Frozen Gloves",
                            Name = "Damian",
                            SpecialAttack = 371,
                            SpecialDefense = 325,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 138
                        },
                        new
                        {
                            Id = new Guid("0e9f84a1-13f0-4892-a23b-f247b0fe98ef"),
                            Attack = 660,
                            Defense = 32,
                            HealthPoints = 246,
                            KnownFrom = "Licensed Metal Cheese",
                            Name = "Emilie",
                            SpecialAttack = 143,
                            SpecialDefense = 499,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 284
                        },
                        new
                        {
                            Id = new Guid("45d62ae3-e516-4c58-bb9c-a1b574a6d259"),
                            Attack = 433,
                            Defense = 473,
                            HealthPoints = 647,
                            KnownFrom = "Intelligent Rubber Mouse",
                            Name = "Prudence",
                            SpecialAttack = 282,
                            SpecialDefense = 475,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 287
                        },
                        new
                        {
                            Id = new Guid("b9a433ee-0947-4a77-9c3f-f48d9fa7d4e5"),
                            Attack = 507,
                            Defense = 424,
                            HealthPoints = 525,
                            KnownFrom = "Awesome Rubber Sausages",
                            Name = "Jayden",
                            SpecialAttack = 34,
                            SpecialDefense = 379,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 492
                        },
                        new
                        {
                            Id = new Guid("b7742c0a-02eb-402c-9724-74a8c2adae29"),
                            Attack = 36,
                            Defense = 118,
                            HealthPoints = 35,
                            KnownFrom = "Handmade Soft Towels",
                            Name = "Raphaelle",
                            SpecialAttack = 83,
                            SpecialDefense = 250,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 697
                        },
                        new
                        {
                            Id = new Guid("f80375a1-a185-4dc7-8ef2-62109d645444"),
                            Attack = 692,
                            Defense = 569,
                            HealthPoints = 346,
                            KnownFrom = "Handmade Metal Keyboard",
                            Name = "Eldora",
                            SpecialAttack = 457,
                            SpecialDefense = 201,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 422
                        },
                        new
                        {
                            Id = new Guid("defca90e-db78-4a62-93b0-95a3a6b35133"),
                            Attack = 384,
                            Defense = 421,
                            HealthPoints = 316,
                            KnownFrom = "Unbranded Steel Pizza",
                            Name = "Emanuel",
                            SpecialAttack = 14,
                            SpecialDefense = 85,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 709
                        },
                        new
                        {
                            Id = new Guid("706dd914-e0a9-4aa6-8c98-16ece935cdd1"),
                            Attack = 133,
                            Defense = 239,
                            HealthPoints = 149,
                            KnownFrom = "Unbranded Frozen Gloves",
                            Name = "Clara",
                            SpecialAttack = 294,
                            SpecialDefense = 488,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 120
                        },
                        new
                        {
                            Id = new Guid("fcbc29e1-2e26-4536-a123-1857114a30b5"),
                            Attack = 52,
                            Defense = 160,
                            HealthPoints = 153,
                            KnownFrom = "Ergonomic Granite Bike",
                            Name = "Johnson",
                            SpecialAttack = 587,
                            SpecialDefense = 383,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 317
                        },
                        new
                        {
                            Id = new Guid("db163d11-8e55-4f88-92b7-011c9843dea0"),
                            Attack = 426,
                            Defense = 460,
                            HealthPoints = 17,
                            KnownFrom = "Refined Granite Salad",
                            Name = "Hertha",
                            SpecialAttack = 245,
                            SpecialDefense = 436,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 202
                        },
                        new
                        {
                            Id = new Guid("1fcaa917-68c7-45bf-b249-35b267eb9e99"),
                            Attack = 672,
                            Defense = 367,
                            HealthPoints = 422,
                            KnownFrom = "Fantastic Concrete Towels",
                            Name = "Roderick",
                            SpecialAttack = 421,
                            SpecialDefense = 633,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 690
                        },
                        new
                        {
                            Id = new Guid("1a8c1659-29fb-4e90-b9ad-92b7f60f2de1"),
                            Attack = 413,
                            Defense = 345,
                            HealthPoints = 622,
                            KnownFrom = "Gorgeous Cotton Chicken",
                            Name = "Marlon",
                            SpecialAttack = 564,
                            SpecialDefense = 237,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 740
                        },
                        new
                        {
                            Id = new Guid("e3b13c49-f9b8-4ae7-b1a7-b0f54a3d6168"),
                            Attack = 305,
                            Defense = 484,
                            HealthPoints = 357,
                            KnownFrom = "Licensed Granite Bacon",
                            Name = "Preston",
                            SpecialAttack = 23,
                            SpecialDefense = 575,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 278
                        },
                        new
                        {
                            Id = new Guid("32617e0d-4ceb-4d47-b162-616a3fe4cffd"),
                            Attack = 69,
                            Defense = 270,
                            HealthPoints = 456,
                            KnownFrom = "Handmade Cotton Computer",
                            Name = "Nichole",
                            SpecialAttack = 460,
                            SpecialDefense = 225,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 2
                        },
                        new
                        {
                            Id = new Guid("5cfbe299-657c-46a7-8255-93a5c9f379d0"),
                            Attack = 425,
                            Defense = 408,
                            HealthPoints = 225,
                            KnownFrom = "Refined Frozen Shirt",
                            Name = "Pierre",
                            SpecialAttack = 352,
                            SpecialDefense = 206,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 222
                        },
                        new
                        {
                            Id = new Guid("0b4971fc-1e34-4fec-acb0-1fa90a5bca90"),
                            Attack = 125,
                            Defense = 564,
                            HealthPoints = 447,
                            KnownFrom = "Fantastic Soft Soap",
                            Name = "Werner",
                            SpecialAttack = 320,
                            SpecialDefense = 28,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 694
                        },
                        new
                        {
                            Id = new Guid("d0c283e2-dd10-46f3-93b8-8caaf0d46871"),
                            Attack = 284,
                            Defense = 578,
                            HealthPoints = 451,
                            KnownFrom = "Awesome Rubber Table",
                            Name = "Meredith",
                            SpecialAttack = 609,
                            SpecialDefense = 415,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 680
                        },
                        new
                        {
                            Id = new Guid("32b1f5a9-9db1-42c2-a485-8e72362eb75d"),
                            Attack = 383,
                            Defense = 508,
                            HealthPoints = 26,
                            KnownFrom = "Tasty Cotton Bike",
                            Name = "Stephany",
                            SpecialAttack = 617,
                            SpecialDefense = 6,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 201
                        },
                        new
                        {
                            Id = new Guid("2915071f-d31d-40b4-9007-553106afaa2f"),
                            Attack = 403,
                            Defense = 322,
                            HealthPoints = 568,
                            KnownFrom = "Sleek Granite Computer",
                            Name = "Christophe",
                            SpecialAttack = 335,
                            SpecialDefense = 357,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 21
                        },
                        new
                        {
                            Id = new Guid("6e16706a-323b-4c93-bae5-f112b0d0687f"),
                            Attack = 241,
                            Defense = 639,
                            HealthPoints = 441,
                            KnownFrom = "Refined Granite Car",
                            Name = "Neha",
                            SpecialAttack = 473,
                            SpecialDefense = 17,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 555
                        },
                        new
                        {
                            Id = new Guid("a48cc454-cb8c-419e-a9f9-fd4e84b6458b"),
                            Attack = 691,
                            Defense = 199,
                            HealthPoints = 568,
                            KnownFrom = "Handmade Rubber Shirt",
                            Name = "Unique",
                            SpecialAttack = 258,
                            SpecialDefense = 190,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 602
                        },
                        new
                        {
                            Id = new Guid("c170a504-540d-4ed7-b93d-a632a8b0d1e1"),
                            Attack = 162,
                            Defense = 104,
                            HealthPoints = 539,
                            KnownFrom = "Sleek Fresh Computer",
                            Name = "Erica",
                            SpecialAttack = 507,
                            SpecialDefense = 204,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 685
                        },
                        new
                        {
                            Id = new Guid("07a7a734-92dd-4fb1-8c5d-c1abb49861bf"),
                            Attack = 629,
                            Defense = 20,
                            HealthPoints = 665,
                            KnownFrom = "Rustic Plastic Cheese",
                            Name = "Burnice",
                            SpecialAttack = 514,
                            SpecialDefense = 375,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 558
                        },
                        new
                        {
                            Id = new Guid("79fab976-49e5-44e3-ae04-d118167fb143"),
                            Attack = 143,
                            Defense = 640,
                            HealthPoints = 445,
                            KnownFrom = "Sleek Fresh Cheese",
                            Name = "Demarcus",
                            SpecialAttack = 282,
                            SpecialDefense = 177,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 10
                        },
                        new
                        {
                            Id = new Guid("e3ae5684-09c1-47bb-b55d-1124cd5543c5"),
                            Attack = 345,
                            Defense = 588,
                            HealthPoints = 242,
                            KnownFrom = "Licensed Plastic Computer",
                            Name = "Casey",
                            SpecialAttack = 486,
                            SpecialDefense = 460,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 96
                        },
                        new
                        {
                            Id = new Guid("3dd4fcb1-8b16-491c-ac6a-e20687779964"),
                            Attack = 562,
                            Defense = 475,
                            HealthPoints = 586,
                            KnownFrom = "Generic Frozen Mouse",
                            Name = "Myrna",
                            SpecialAttack = 233,
                            SpecialDefense = 456,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 354
                        },
                        new
                        {
                            Id = new Guid("b4a9a8cc-d727-45d5-833b-393b65706532"),
                            Attack = 445,
                            Defense = 438,
                            HealthPoints = 242,
                            KnownFrom = "Incredible Soft Pants",
                            Name = "Bonnie",
                            SpecialAttack = 431,
                            SpecialDefense = 109,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 651
                        },
                        new
                        {
                            Id = new Guid("2363c518-1efd-446c-abcc-808a38811869"),
                            Attack = 334,
                            Defense = 464,
                            HealthPoints = 662,
                            KnownFrom = "Gorgeous Wooden Cheese",
                            Name = "Violet",
                            SpecialAttack = 369,
                            SpecialDefense = 362,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 272
                        },
                        new
                        {
                            Id = new Guid("0b6a6f96-4786-450c-a620-7e42097da7d2"),
                            Attack = 654,
                            Defense = 195,
                            HealthPoints = 119,
                            KnownFrom = "Ergonomic Plastic Salad",
                            Name = "Antoinette",
                            SpecialAttack = 131,
                            SpecialDefense = 40,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 526
                        },
                        new
                        {
                            Id = new Guid("d56ab89b-f0a4-4edf-99d7-3f56c029e8a5"),
                            Attack = 181,
                            Defense = 399,
                            HealthPoints = 492,
                            KnownFrom = "Generic Wooden Shoes",
                            Name = "Elsa",
                            SpecialAttack = 257,
                            SpecialDefense = 319,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 558
                        },
                        new
                        {
                            Id = new Guid("68e227d3-4a62-4913-b377-174eb75a857a"),
                            Attack = 441,
                            Defense = 631,
                            HealthPoints = 684,
                            KnownFrom = "Awesome Concrete Chair",
                            Name = "Elwyn",
                            SpecialAttack = 621,
                            SpecialDefense = 343,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 714
                        },
                        new
                        {
                            Id = new Guid("dee9e3e5-aa3c-4c94-ae89-97bfb1994ce0"),
                            Attack = 491,
                            Defense = 143,
                            HealthPoints = 252,
                            KnownFrom = "Awesome Wooden Mouse",
                            Name = "Esperanza",
                            SpecialAttack = 177,
                            SpecialDefense = 404,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 810
                        },
                        new
                        {
                            Id = new Guid("b6363fc3-3b81-4966-99a3-7183caf46578"),
                            Attack = 568,
                            Defense = 379,
                            HealthPoints = 100,
                            KnownFrom = "Unbranded Fresh Tuna",
                            Name = "Keshaun",
                            SpecialAttack = 338,
                            SpecialDefense = 537,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 89
                        },
                        new
                        {
                            Id = new Guid("d248de2f-2363-4241-a4b7-8c390c72c3d1"),
                            Attack = 612,
                            Defense = 405,
                            HealthPoints = 214,
                            KnownFrom = "Handmade Frozen Chips",
                            Name = "Cleo",
                            SpecialAttack = 499,
                            SpecialDefense = 200,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 180
                        },
                        new
                        {
                            Id = new Guid("2274c5dc-9725-4009-b016-1f48dc90579d"),
                            Attack = 561,
                            Defense = 203,
                            HealthPoints = 597,
                            KnownFrom = "Unbranded Frozen Pizza",
                            Name = "Hunter",
                            SpecialAttack = 478,
                            SpecialDefense = 14,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 559
                        },
                        new
                        {
                            Id = new Guid("35ac1ae0-5489-47c4-afea-f4a6e591c8d1"),
                            Attack = 658,
                            Defense = 85,
                            HealthPoints = 22,
                            KnownFrom = "Incredible Wooden Fish",
                            Name = "Jude",
                            SpecialAttack = 351,
                            SpecialDefense = 218,
                            SpeciesId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Speed = 661
                        });
                });

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Taxonomy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Monkey", b =>
                {
                    b.HasOne("MonkeyMon_Blazor.Models.Species", "Species")
                        .WithMany("Monkeys")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("MonkeyMon_Blazor.Models.Species", b =>
                {
                    b.Navigation("Monkeys");
                });
#pragma warning restore 612, 618
        }
    }
}
